import type { NextPage } from "next";
import Head from "next/head";
import { BudgetBalance } from "src/modules/budgets/containers/BudgetBalance";
import { useNodeBudgetsRepository } from "src/modules/budgets/service/useNodeBudgets.repository";
import { useBudgetBalanceState } from "src/modules/budgets/store/useBalanceState";
import styles from "styles/Home.module.css";

const HomePage: NextPage = () => {
  const { balance, budgetBalanceStore } = useBudgetBalanceState();
  const budgetsRepository = useNodeBudgetsRepository();

  return (
    <div className={styles.container}>
      <Head>
        <title>Budget Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BudgetBalance
          balance={balance}
          budgetsRepository={budgetsRepository}
          budgetBalanceStore={budgetBalanceStore}
        />

        <p>{balance}</p>
      </main>
    </div>
  );
};

export default HomePage;
