import Head from "next/head";
import { AuthenticationLayout } from "src/modules/auth/components/AuthenticationLayout";
import { PrivateRoute } from "src/modules/auth/containers/PrivateRoute";
import { BudgetBalance } from "src/modules/budgets/containers/BudgetBalance";
import { useNodeBudgetsRepository } from "src/modules/budgets/service/useNodeBudgets.repository";
import { MovementsMostRecents } from "src/modules/movements/containers/MovementsMostRecents";
import { useNodeMovementsRepository } from "src/modules/movements/service/useNodeMovements.repository";
import { MainLayout } from "src/modules/shared/components/MainLayout";

export default function HomePage() {
  const budgetsRepository = useNodeBudgetsRepository();
  const movementsRepository = useNodeMovementsRepository();

  return (
    <div>
      <Head>
        <title>Budget Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BudgetBalance budgetsRepository={budgetsRepository} />

        <MovementsMostRecents movementsRepository={movementsRepository} />
      </main>
    </div>
  );
}

HomePage.getLayout = function (page: React.ReactElement) {
  return (
    <>
      <AuthenticationLayout Route={PrivateRoute}>
        <MainLayout>{page}</MainLayout>
      </AuthenticationLayout>
    </>
  );
};
