import Head from "next/head";
import { AuthenticationLayout } from "src/modules/auth/components/AuthenticationLayout";
import { PrivateRoute } from "src/modules/auth/containers/PrivateRoute";
import { BudgetBalance } from "src/modules/budgets/containers/BudgetBalance";
import { useNodeBudgetsRepository } from "src/modules/budgets/service/useNodeBudgets.repository";
import { useBudgetBalanceState } from "src/modules/budgets/store/useBalanceState";
import { MovementsMostRecents } from "src/modules/movements/containers/MovementsMostRecents";
import { useNodeMovementsRepository } from "src/modules/movements/service/useNodeMovements.repository";
import { MainLayout } from "src/modules/shared/components/MainLayout";
import styles from "styles/Home.module.css";

export default function HomePage() {
  const { balance, budgetBalanceStore } = useBudgetBalanceState();
  const budgetsRepository = useNodeBudgetsRepository();

  const movementsRepository = useNodeMovementsRepository();
  return (
    <div className={styles.container}>
      <Head>
        <title>Budget Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BudgetBalance
          balance={balance}
          budgetsRepository={budgetsRepository}
          budgetBalanceStore={budgetBalanceStore}
        />

        <MovementsMostRecents movementsRepository={movementsRepository} />
      </main>
    </div>
  );
}

HomePage.getLayout = function (page: React.ReactElement) {
  return (
    <>
      <AuthenticationLayout Route={PrivateRoute}>
        <MainLayout>{page}</MainLayout>
      </AuthenticationLayout>
    </>
  );
};
